=== russell-todd-sorensen/semitasker/hom/participants/data/tblExtContInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="tblExtContInfo" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="tblExtContInfo">
<xsd:annotation>
<xsd:appinfo>
<od:tableProperty name="GUID" type="9" value="GVwyQGS4LEmHhL1cWRUZxg==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="1"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAAZXDJAZLgsSYeEvVxZFRnGAAAAABGfEzPO8eRAAAAAAAAAAAB0AGIA
bABFAHgAdABDAG8AbgB0AEkAbgBmAG8AAAAAAAAACRznkRvG80SB98Sdh5l2egcA
AAAZXDJAZLgsSYeEvVxZFRnGTABhAHMAdABOAGEAbQBlAAAAAAAAAGGNLxhYqTpH
kuolxr1WP1IHAAAAGVwyQGS4LEmHhL1cWRUZxkUAeAB0AFUAbgBpAHEAdQBlAAAA
AAAAAGlzBpvFVRdOhIjDflardssHAAAAGVwyQGS4LEmHhL1cWRUZxkUAeAB0AEMA
bwBuAHQAVAB5AHAAZQAAAAAAAADvC7zNB5xNS7Ocx+wgs3K6BwAAABlcMkBkuCxJ
h4S9XFkVGcZGAGkAcgBzAHQATgBhAG0AZQAAAAAAAABrMCw4SHouRpkbbNmF0uBF
BwAAABlcMkBkuCxJh4S9XFkVGcZFAHgAdABDAG8AbgB0AEUAbQBhAGkAbAAAAAAA
AAB9Bu9BU4XhRpbmYf2/V7KVBwAAABlcMkBkuCxJh4S9XFkVGcZFAHgAdABDAG8A
bgB0AFAAaABvAG4AZQAAAAAAAACZXbPefXkIRpBHrVrfOZqqBwAAABlcMkBkuCxJ
h4S9XFkVGcZPAGYAZgBpAGMAZQAAAAAAAABb6/xB6k3lQanbl5pKBy8eBwAAABlc
MkBkuCxJh4S9XFkVGcZFAHgAdABDAG8AbgB0AEMAZQBsAAAAAAAAAOuzVvZPn2xH
o3Ge5TCObxgHAAAAGVwyQGS4LEmHhL1cWRUZxkYAdQBsAGwATgBhAG0AZQAAAAAA
AADeA5Uia7IcRZShv5gBZKwkBwAAABlcMkBkuCxJh4S9XFkVGcZMAG8AYwBhAHQA
aQBvAG4AAAAAAAAACrG8o5GLUU+kSwmj6mljVgcAAAAZXDJAZLgsSYeEvVxZFRnG
VAB5AHAAZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAUAAAAAAAAAAAAAAAAA
AAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="100"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="OrderBy" type="12" value="[tblExtContInfo].[LastName]"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ExtUnique" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ExtContType" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="100"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="LastName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="100"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="FirstName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="100"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="ExtContEmail" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="100"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="ExtContPhone" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="100"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Office" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="100"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="ExtContCel" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="100"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="FullName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="100"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Location" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="100"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Type" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== russell-todd-sorensen/semitasker/hom/participants/data/tblExtContInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="tblExtContInfo.xsd" generated="2017-09-14T13:48:56">
<tblExtContInfo>
<ExtUnique>345</ExtUnique>
<ExtContType>CC3</ExtContType>
<LastName>Albertsen</LastName>
<ExtContEmail>ppalbertsen@doc1wa.gov</ExtContEmail>
<ExtContPhone>36042644335462</ExtContPhone>
<Location>WCC</Location>
<Type>1</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>284</ExtUnique>
<ExtContType>CC3</ExtContType>
<LastName>Aleksinski</LastName>
<ExtContEmail>rlaleksinski@doc1.wa.gov</ExtContEmail>
<ExtContPhone>360-537-1986</ExtContPhone>
<Location>SCCC</Location>
<Type>1</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>316</ExtUnique>
<ExtContType>CC3</ExtContType>
<LastName>Alvarez</LastName>
<ExtContEmail>dhalvarez@doc1.wa.gov</ExtContEmail>
<ExtContPhone>36042644335701</ExtContPhone>
<Location>WCC</Location>
<Type>1</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>34</ExtUnique>
<ExtContType>CCO</ExtContType>
<LastName>Amaya</LastName>
<FirstName>Jessica</FirstName>
<ExtContEmail>Jessica.amaya@doc.wa.gov</ExtContEmail>
<ExtContPhone>2069333410</ExtContPhone>
<FullName>Jessica Amaya</FullName>
<Type>4</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>279</ExtUnique>
<ExtContType>CC3</ExtContType>
<LastName>Anderson</LastName>
<ExtContPhone>360-537-1800</ExtContPhone>
<Location>SCCC</Location>
<Type>1</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>91</ExtUnique>
<ExtContType>CCO</ExtContType>
<LastName>Bazan</LastName>
<FirstName>Maria</FirstName>
<FullName>Maria Bazan</FullName>
<Type>4</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>314</ExtUnique>
<ExtContType>CC3</ExtContType>
<LastName>Beeman</LastName>
<ExtContEmail>drbeeman@doc1.wa.gov</ExtContEmail>
<ExtContPhone>509-544-3622</ExtContPhone>
<Location>CRCC</Location>
<Type>1</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>354</ExtUnique>
<ExtContType>CC3</ExtContType>
<LastName>Bonnell</LastName>
<ExtContEmail>jmbonnell@doc1.wa.gov</ExtContEmail>
<ExtContPhone>509-544-3623</ExtContPhone>
<Location>CRCC</Location>
<Type>1</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>323</ExtUnique>
<ExtContType>CC3</ExtContType>
<LastName>Boucher</LastName>
<ExtContEmail>bhboucher@doc1.wa.gov</ExtContEmail>
<ExtContPhone>509-544-3660</ExtContPhone>
<Location>CRCC</Location>
<Type>1</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>393</ExtUnique>
<ExtContType>CC3</ExtContType>
<LastName>bramhall</LastName>
<FirstName>STEVE</FirstName>
<ExtContEmail>stbramhall@doc1.wa.gov</ExtContEmail>
<ExtContPhone>509-543-5946</ExtContPhone>
<FullName>STEVE bramhall</FullName>
<Type>1</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>417</ExtUnique>
<ExtContType>CCO</ExtContType>
<LastName>Bullard</LastName>
<FirstName>Mary</FirstName>
<ExtContEmail>mjbullard@doc1.wa.gov</ExtContEmail>
<ExtContPhone>206-549-1723</ExtContPhone>
<FullName>Mary Bullard</FullName>
<Type>4</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>416</ExtUnique>
<ExtContType>CCO</ExtContType>
<LastName>Bullard</LastName>
<FirstName>Mary</FirstName>
<ExtContEmail>mjbullard@doc1.wa.gov</ExtContEmail>
<ExtContPhone>206-549-1723</ExtContPhone>
<FullName>Mary Bullard</FullName>
<Type>4</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>17</ExtUnique>
<ExtContType>CCO</ExtContType>
<LastName>Bullard</LastName>
<FirstName>Mary</FirstName>
<ExtContEmail>mjbullard@doc1.wa.gov</ExtContEmail>
<FullName>Mary Bullard</FullName>
<Type>4</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>378</ExtUnique>
<ExtContType>Other</ExtContType>
<LastName>Burk</LastName>
<FirstName>Christal</FirstName>
<Location>Frontier Beh Health</Location>
<Type>3</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>363</ExtUnique>
<ExtContType>CC3</ExtContType>
<LastName>Burns</LastName>
<ExtContEmail>smburns@DOC1.WA.GOV</ExtContEmail>
<ExtContPhone>360-794-2535</ExtContPhone>
<Location>TRU</Location>
<Type>1</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>23</ExtUnique>
<ExtContType>CCO</ExtContType>
<LastName>Butler</LastName>
<FirstName>Susan</FirstName>
<FullName>Susan Butler</FullName>
<Type>4</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>319</ExtUnique>
<ExtContType>CC3</ExtContType>
<LastName>Butler</LastName>
<ExtContEmail>mbutler@doc1.wa.gov</ExtContEmail>
<ExtContPhone>3604264692</ExtContPhone>
<Location>WCC</Location>
<Type>1</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>366</ExtUnique>
<ExtContType>Other</ExtContType>
<LastName>Camille Iorio</LastName>
<ExtContEmail>camille.iorio@farestart.org</ExtContEmail>
<ExtContPhone>206-787-1520</ExtContPhone>
<Location>FareStart</Location>
<Type>3</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>79</ExtUnique>
<ExtContType>SOTP</ExtContType>
<LastName>Cardona</LastName>
<FirstName>Walter</FirstName>
<ExtContPhone>2064450620</ExtContPhone>
<FullName>Walter Cardona</FullName>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>24</ExtUnique>
<ExtContType>CCO</ExtContType>
<LastName>Carillo</LastName>
<FirstName>Kim</FirstName>
<FullName>Kim Carillo</FullName>
<Type>4</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>72</ExtUnique>
<ExtContType>CCO</ExtContType>
<LastName>Carpenter</LastName>
<FirstName>Ron</FirstName>
<FullName>Ron Carpenter</FullName>
<Type>4</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>13</ExtUnique>
<ExtContType>CCO</ExtContType>
<LastName>Casos</LastName>
<FirstName>John</FirstName>
<ExtContEmail>jjcasos@doc1.wa.gov</ExtContEmail>
<FullName>John Casos</FullName>
<Type>4</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>11</ExtUnique>
<ExtContType>CCO</ExtContType>
<LastName>Castillo</LastName>
<FirstName>Jermaine</FirstName>
<ExtContEmail>jocastillo@doc1.wa.gov</ExtContEmail>
<ExtContPhone>2068357484</ExtContPhone>
<ExtContCel>2064509807</ExtContCel>
<FullName>Jermaine Castillo</FullName>
<Type>4</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>102</ExtUnique>
<ExtContType>USPO</ExtContType>
<LastName>Cavendish</LastName>
<FirstName>Sarah</FirstName>
<ExtContPhone>2536777695</ExtContPhone>
<FullName>Sarah Cavendish</FullName>
<Location>Federal Detention</Location>
<Type>2</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>321</ExtUnique>
<ExtContType>USPO</ExtContType>
<LastName>Cavendish</LastName>
<ExtContEmail>sarah_cavendish@wawp.uscourts.gov</ExtContEmail>
<ExtContPhone>253-677-7695</ExtContPhone>
<Location>Federal Detention</Location>
<Type>2</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>360</ExtUnique>
<ExtContType>Other</ExtContType>
<LastName>Charmaine Day</LastName>
<ExtContPhone>206-276-2664</ExtContPhone>
<Location>King County Shelter</Location>
<Type>3</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>93</ExtUnique>
<ExtContType>SOTP</ExtContType>
<LastName>Christison</LastName>
<FirstName>Nicole</FirstName>
<FullName>Nicole Christison</FullName>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>377</ExtUnique>
<ExtContType>CC3</ExtContType>
<LastName>Christner</LastName>
<FirstName>Chris</FirstName>
<ExtContEmail>smchristner@doc1.wa.gov</ExtContEmail>
<ExtContPhone>3607942536</ExtContPhone>
<Location>TRU</Location>
<Type>1</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>374</ExtUnique>
<ExtContType>Other</ExtContType>
<LastName>Clark</LastName>
<FirstName>Jamie</FirstName>
<ExtContEmail>jclark1@fbhwa.org</ExtContEmail>
<ExtContPhone>5098384651248105</ExtContPhone>
<Location>Frontier Beh Health</Location>
<Type>3</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>38</ExtUnique>
<ExtContType>CCO</ExtContType>
<LastName>Cobb</LastName>
<FirstName>Gregory</FirstName>
<ExtContEmail>gregroy.cobb@doc.wa.gov</ExtContEmail>
<ExtContPhone>2069333409</ExtContPhone>
<FullName>Gregory Cobb</FullName>
<Type>4</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>68</ExtUnique>
<ExtContType>CCO</ExtContType>
<LastName>Coleman</LastName>
<FirstName>Michael</FirstName>
<ExtContEmail>mjcoleman@doc1.wa.gov</ExtContEmail>
<FullName>Michael Coleman</FullName>
<Type>4</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>52</ExtUnique>
<ExtContType>CCO</ExtContType>
<LastName>Combs</LastName>
<FirstName>Lisa</FirstName>
<FullName>Lisa Combs</FullName>
<Type>4</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>26</ExtUnique>
<ExtContType>CCO</ExtContType>
<LastName>Conrad</LastName>
<FirstName>Nathan</FirstName>
<ExtContEmail>nwrconrad@doc1.wa.gov</ExtContEmail>
<ExtContPhone>2068357480</ExtContPhone>
<FullName>Nathan Conrad</FullName>
<Type>4</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>64</ExtUnique>
<ExtContType>CCO</ExtContType>
<LastName>Contine</LastName>
<FirstName>Brenda</FirstName>
<ExtContEmail>bjcontine@doc1.wa.gov</ExtContEmail>
<FullName>Brenda Contine</FullName>
<Type>4</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>283</ExtUnique>
<ExtContType>CC3</ExtContType>
<LastName>Cook</LastName>
<ExtContEmail>pecook@doc1.wa.gov</ExtContEmail>
<ExtContPhone>509-543-5887</ExtContPhone>
<Location>CRCC</Location>
<Type>1</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>330</ExtUnique>
<ExtContType>CC3</ExtContType>
<LastName>Courtney</LastName>
<ExtContEmail>jcourtney@doc1.wa.gov</ExtContEmail>
<ExtContPhone>506-526-6345</ExtContPhone>
<Location>WSP</Location>
<Type>1</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>41</ExtUnique>
<ExtContType>CCO</ExtContType>
<LastName>Cronk</LastName>
<FirstName>Brett</FirstName>
<ExtContEmail>bacronk@doc1.wa.gov</ExtContEmail>
<FullName>Brett Cronk</FullName>
<Type>4</Type>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>89</ExtUnique>
<ExtContType>SOTP</ExtContType>
<LastName>Cummings</LastName>
<FirstName>Matt</FirstName>
<FullName>Matt Cummings</FullName>
</tblExtContInfo>
<tblExtContInfo>
<ExtUnique>396</ExtUnique>
<ExtContType>CC3</ExtContType>
<LastName>dalgleish</LastName>
<FirstName>Steven</FirstName>
<ExtContEmail>sgdalgleish@doc1.wa.gov</ExtContEmail>
